#!/bin/bash

# Sanity check scenario
# Tests basic functionality and parsing

# Start the server
simulation_server --min-reply-delay-ms=10 --max-reply-delay-ms=100 --test-duration-seconds=20 &

simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=20 &

sleep 20

