/// Environment variable name aliases.
/// Format: ("<Current Env Name>", "<Alternate name to check>")
/// These aliases support backward compatibility with old environment variable names
/// from before the config refactor (when constants were in data/src/constants.rs and cas_client/src/constants.rs).
pub const ENVIRONMENT_NAME_ALIASES: &[(&str, &str)] = &[
    // Older environment variable names that we should check for backward compatibility.
    ("HF_XET_CLIENT_UPLOAD_REPORTING_BLOCK_SIZE", "HF_XET_UPLOAD_REPORTING_BLOCK_SIZE"),
    (
        "HF_XET_DATA_MIN_SPACING_BETWEEN_GLOBAL_DEDUP_QUERIES",
        "HF_XET_MIN_SPACING_BETWEEN_GLOBAL_DEDUP_QUERIES",
    ),
    ("HF_XET_DATA_LOCAL_CAS_SCHEME", "HF_XET_LOCAL_CAS_SCHEME"),
    ("HF_XET_DATA_CURRENT_VERSION", "HF_XET_CURRENT_VERSION"),
    ("HF_XET_DATA_MAX_CONCURRENT_FILE_INGESTION", "HF_XET_MAX_CONCURRENT_FILE_INGESTION"),
    ("HF_XET_DATA_INGESTION_BLOCK_SIZE", "HF_XET_INGESTION_BLOCK_SIZE"),
    ("HF_XET_DATA_PROGRESS_UPDATE_INTERVAL", "HF_XET_PROGRESS_UPDATE_INTERVAL"),
    ("HF_XET_DATA_PROGRESS_UPDATE_SPEED_SAMPLING_WINDOW", "HF_XET_PROGRESS_UPDATE_SPEED_SAMPLING_WINDOW"),
    ("HF_XET_DATA_SESSION_XORB_METADATA_FLUSH_INTERVAL", "HF_XET_SESSION_XORB_METADATA_FLUSH_INTERVAL"),
    ("HF_XET_DATA_SESSION_XORB_METADATA_FLUSH_MAX_COUNT", "HF_XET_SESSION_XORB_METADATA_FLUSH_MAX_COUNT"),
    // shard config was previously named mdb_shard / metadata_shard; support old prefixes
    ("HF_XET_SHARD_TARGET_SIZE", "HF_XET_MDB_SHARD_TARGET_SIZE"),
    ("HF_XET_SHARD_MAX_TARGET_SIZE", "HF_XET_MDB_SHARD_MAX_TARGET_SIZE"),
    ("HF_XET_SHARD_CACHE_SIZE_LIMIT", "HF_XET_MDB_SHARD_CACHE_SIZE_LIMIT"),
    ("HF_XET_SHARD_CHUNK_INDEX_TABLE_MAX_SIZE", "HF_XET_MDB_SHARD_CHUNK_INDEX_TABLE_MAX_SIZE"),
    ("HF_XET_SHARD_CHUNK_INDEX_TABLE_MAX_SIZE", "HF_XET_CHUNK_INDEX_TABLE_MAX_SIZE"),
    // xorb compression fields were previously in the data group; support old HF_XET_DATA_XORB_* names
    (
        "HF_XET_XORB_COMPRESSION_SCHEME_RETEST_INTERVAL",
        "HF_XET_DATA_XORB_COMPRESSION_SCHEME_RETEST_INTERVAL",
    ),
    ("HF_XET_XORB_COMPRESSION_POLICY", "HF_XET_DATA_XORB_COMPRESSION_POLICY"),
    // Fixed concurrency aliases - these set initial, min, and max to the same value
    ("HF_XET_CLIENT_AC_INITIAL_UPLOAD_CONCURRENCY", "HF_XET_FIXED_UPLOAD_CONCURRENCY"),
    ("HF_XET_CLIENT_AC_MIN_UPLOAD_CONCURRENCY", "HF_XET_FIXED_UPLOAD_CONCURRENCY"),
    ("HF_XET_CLIENT_AC_MAX_UPLOAD_CONCURRENCY", "HF_XET_FIXED_UPLOAD_CONCURRENCY"),
    ("HF_XET_CLIENT_AC_INITIAL_DOWNLOAD_CONCURRENCY", "HF_XET_FIXED_DOWNLOAD_CONCURRENCY"),
    ("HF_XET_CLIENT_AC_MIN_DOWNLOAD_CONCURRENCY", "HF_XET_FIXED_DOWNLOAD_CONCURRENCY"),
    ("HF_XET_CLIENT_AC_MAX_DOWNLOAD_CONCURRENCY", "HF_XET_FIXED_DOWNLOAD_CONCURRENCY"),
];
