name: 'Disable git user checks'
description: 'Allow git user and repository owner to differ'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo git config --system --add safe.directory '*'