[package]
name = "cas_object"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
bincode = "1.3.3"
http = "1.1.0"
merklehash = { path = "../merklehash" }
tempfile = "3.12.0"
tracing = "0.1.40"
xet_error = { path = "../xet_error" }

[dev-dependencies]
rand = "0.8.5"
tempfile = "3.12.0"
