#!/bin/bash

# Simulates multiple download client running in parallel

# Start the server
simulation_server --min-reply-delay-ms=400 --max-reply-delay-ms=1200 --test-duration-seconds=600 &

echo "Testing a download of mixed sizes."
simulation_client --min-data-kb=1 --max-data-kb=65536 --repeat-duration-seconds=600 &
sleep 100
simulation_client --min-data-kb=1 --max-data-kb=65536 --repeat-duration-seconds=500 &
sleep 100
simulation_client --min-data-kb=1 --max-data-kb=65536 --repeat-duration-seconds=400 &
sleep 100
simulation_client --min-data-kb=1 --max-data-kb=65536 --repeat-duration-seconds=300 &
sleep 100
simulation_client --min-data-kb=1 --max-data-kb=65536 --repeat-duration-seconds=200 &
sleep 100
simulation_client --min-data-kb=1 --max-data-kb=65536 --repeat-duration-seconds=100 &
sleep 100