#!/bin/bash

# Simulates a burst of xorb uploads. 

# Start the server
simulation_server --min-reply-delay-ms=300 --max-reply-delay-ms=1200 --test-duration-seconds=600 &

echo "Testing a burst of simultaneous short uploads, with several longer ones."
simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=600 &
simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=500 &
simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=500 &
simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=400 &
simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=400 &
simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=300 &
simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=300 &
simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=200 &
simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=200 &
simulation_client --min-data-kb=49152 --max-data-kb=65536 --repeat-duration-seconds=100 &

sleep 600
