[package]
name = "xet-mount"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "xet-mount"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
uuid = { workspace = true }

cas_types = { path = "../cas_types" }
cas_client = { path = "../cas_client" }
data = { path = "../data" }
hub_client = { path = "../hub_client" }
merklehash = { path = "../merklehash" }
utils = { path = "../utils" }

nfsserve = { git = "https://github.com/huggingface/nfsserve.git" }
