[package]
name = "xet-mount"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "xet-mount"
path = "src/main.rs"

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

cas_types = { path = "../cas_types" }
data = { path = "../data" }
hub_client = { path = "../hub_client" }
merklehash = { path = "../merklehash" }

nfsserve = { git = "https://github.com/huggingface/nfsserve.git" }
