[package]
name = "xet_threadpool"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["sync", "macros", "rt", "time", "io-util"] }
thiserror = { workspace = true }
tracing = { workspace = true }
lazy_static = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
