[package]
name = "chunker-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
deduplication = {path = "../deduplication"}
serde = { version = "1.0.219", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
