/* Generated by cbindgen from xet_capi. DO NOT EDIT BY HAND. */

#ifndef HF_XET_H
#define HF_XET_H

/* Regenerate with `cargo build -p xet_capi`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status returned by every fallible `xet_*` function.
 */
typedef enum {
    XetStatus_XetOk = 0,
    XetStatus_XetErr = 1,
    XetStatus_XetErrInvalidArg = 2,
    XetStatus_XetErrAuth = 3,
    XetStatus_XetErrNotFound = 4,
    XetStatus_XetErrCancelled = 5,
    XetStatus_XetErrPanic = 6,
} XetStatus;

typedef enum {
    XetPollState_XetPollPending = 0,
    XetPollState_XetPollReady = 1,
    XetPollState_XetPollError = 2,
} XetPollState;

/**
 * SHA-256 handling for uploads.
 */
typedef enum {
    XetSha256Policy_XetSha256Compute = 0,
    XetSha256Policy_XetSha256Skip = 1,
    XetSha256Policy_XetSha256Provided = 2,
} XetSha256Policy;

/**
 * An owned byte buffer produced by streaming downloads. Read via
 * [`xet_bytes_data`] / [`xet_bytes_len`]; free with [`xet_bytes_free`].
 */
typedef struct XetBytes XetBytes;

/**
 * Opaque error object. Read via [`xet_error_message`] / [`xet_error_code`];
 * free with [`xet_error_free`].
 */
typedef struct XetError XetError;

/**
 * A queued file download. Free with [`xet_file_download_free`].
 */
typedef struct XetFileDownload XetFileDownload;

/**
 * A file-download group (Arc-backed; cheap to clone). Free with
 * [`xet_file_download_group_free`].
 */
typedef struct XetFileDownloadGroup XetFileDownloadGroup;

/**
 * File descriptor for downloads. Free with [`xet_file_info_free`].
 */
typedef struct XetFileInfo XetFileInfo;

/**
 * Per-file metadata result. C strings are prebuilt at construction so accessor
 * pointers stay valid until the handle is freed. Free OWNED handles (from
 * `xet_op_take_file_metadata`) with [`xet_file_metadata_free`]; borrowed views
 * returned by report accessors must NOT be freed.
 */
typedef struct XetFileMetadataHandle XetFileMetadataHandle;

/**
 * A queued file upload. Free with [`xet_file_upload_free`].
 */
typedef struct XetFileUpload XetFileUpload;

/**
 * A spawned, poll-able operation. Poll with [`xet_op_poll`], then consume with
 * the matching `xet_op_take_*`. Free an un-taken op with [`xet_op_free`].
 */
typedef struct XetOp XetOp;

/**
 * A Xet session. Owns no auth; produces per-commit / per-group auth via the
 * `xet_session_new_*` builders (added in a later task). Free with
 * [`xet_session_free`].
 */
typedef struct XetSession XetSession;

/**
 * A streaming upload handle. Feed data with [`xet_stream_upload_write_start`],
 * then [`xet_stream_upload_finish_start`]. Free with [`xet_stream_upload_free`].
 */
typedef struct XetStreamUpload XetStreamUpload;

/**
 * An upload commit (Arc-backed; cheap to clone). Free with [`xet_upload_commit_free`].
 */
typedef struct XetUploadCommit XetUploadCommit;

/**
 * Flat progress snapshot (all scalar; stable layout).
 */
typedef struct {
    uint64_t total_bytes;
    uint64_t total_bytes_completed;
    uint64_t total_transfer_bytes;
    uint64_t total_transfer_bytes_completed;
} XetProgress;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the xet_capi version as a static NUL-terminated C string.
 */
const char *xet_version(void);

/**
 * # Safety
 * `b` must be null or a valid pointer to a live `XetBytes` produced by this crate.
 */
const unsigned char *xet_bytes_data(const XetBytes *b);

/**
 * # Safety
 * `b` must be null or a valid pointer to a live `XetBytes` produced by this crate.
 */
uintptr_t xet_bytes_len(const XetBytes *b);

void xet_bytes_free(XetBytes *b);

/**
 * Test-only constructor used by ffi_tests.
 */
XetBytes *xet_test_make_bytes(void);

/**
 * Queue a file for download to `dest_path`. Returns a handle immediately;
 * call `xet_file_download_group_finish_start` to await all downloads.
 *
 * # Safety
 * `group`/`file_info` valid handles; `dest_path` a valid C string; `out`/`err` valid.
 */
XetStatus xet_file_download_group_download_to_path(const XetFileDownloadGroup *group,
                                                   const XetFileInfo *file_info,
                                                   const char *dest_path,
                                                   XetFileDownload **out,
                                                   XetError **err);

/**
 * Start awaiting all queued downloads. Poll the returned op; it yields a
 * download-group report.
 *
 * # Safety
 * `group`/`out`/`err` valid pointers.
 */
XetStatus xet_file_download_group_finish_start(const XetFileDownloadGroup *group,
                                               XetOp **out,
                                               XetError **err);

/**
 * # Safety
 * `group` valid; `out` a valid pointer to a `XetProgress`.
 */
XetStatus xet_file_download_group_progress(const XetFileDownloadGroup *group, XetProgress *out);

/**
 * # Safety
 * `group` valid; `err` valid.
 */
XetStatus xet_file_download_group_abort(const XetFileDownloadGroup *group, XetError **err);

/**
 * Returns the download's task id, or 0 if `download` is null.
 *
 * # Safety
 * `download` must be null or a valid handle.
 */
uint64_t xet_file_download_task_id(const XetFileDownload *download);

void xet_file_download_group_free(XetFileDownloadGroup *group);

void xet_file_download_free(XetFileDownload *download);

/**
 * # Safety
 * `err` must be null or a valid pointer to a live `XetError` produced by this crate.
 */
XetStatus xet_error_code(const XetError *err);

/**
 * # Safety
 * `err` must be null or a valid pointer to a live `XetError` produced by this crate.
 */
const char *xet_error_message(const XetError *err);

/**
 * # Safety
 * `err` must be null or a pointer previously returned by this crate that has not
 * already been freed.
 */
void xet_error_free(XetError *err);

/**
 * Test-only constructor used by ffi_tests.
 *
 * # Safety
 * `out` must be a valid, non-null pointer to a writable `*mut XetError`.
 */
int xet_test_make_auth_error(XetError **out);

/**
 * Create a file descriptor from a xet content hash (hex) and size.
 *
 * # Safety
 * `hash` must be a valid NUL-terminated C string; `out` a valid pointer.
 */
XetStatus xet_file_info_new(const char *hash,
                            uint64_t file_size,
                            XetFileInfo **out,
                            XetError **err);

/**
 * Like [`xet_file_info_new`] but with a known SHA-256 (hex).
 *
 * # Safety
 * `hash` and `sha256` must be valid NUL-terminated C strings; `out` valid.
 */
XetStatus xet_file_info_new_with_sha256(const char *hash,
                                        uint64_t file_size,
                                        const char *sha256,
                                        XetFileInfo **out,
                                        XetError **err);

void xet_file_info_free(XetFileInfo *fi);

/**
 * # Safety
 * `op` must be null or a valid pointer to a live `XetOp` produced by this crate.
 */
XetPollState xet_op_poll(const XetOp *op);

/**
 * # Safety
 * `op` must be null or a pointer previously returned by this crate that has not
 * already been freed or consumed by a `xet_op_take_*` call.
 */
void xet_op_free(XetOp *op);

/**
 * Extract a `XetError` from a failed op. Returns `XET_OK` and fills `*err`;
 * returns `XET_ERR_INVALID_ARG` if the op did not fail.
 *
 * # Safety
 * `op` must be a valid pointer to a live `XetOp`; `err` must be null or a valid
 * writable `*mut XetError`.
 */
XetStatus xet_op_take_error(XetOp *op, XetError **err);

/**
 * Void ops (e.g. stream write) — no payload.
 *
 * # Safety
 * `op` must be a valid pointer to a live `XetOp`; `err` must be null or a valid
 * writable `*mut XetError`.
 */
XetStatus xet_op_take_void(XetOp *op, XetError **err);

/**
 * Ordered stream chunk. On success `*out` is a `XetBytes*`, or NULL at EOF.
 *
 * # Safety
 * `op` must be a valid pointer to a live `XetOp`; `out` and `err` must be null
 * or valid writable out-pointers.
 */
XetStatus xet_op_take_bytes(XetOp *op, XetBytes **out, XetError **err);

/**
 * Unordered stream chunk. On success fills `*offset` and `*out` (NULL at EOF).
 *
 * # Safety
 * `op` must be a valid pointer to a live `XetOp`; `offset`, `out`, and `err`
 * must be null or valid writable out-pointers.
 */
XetStatus xet_op_take_chunk(XetOp *op, uint64_t *offset, XetBytes **out, XetError **err);

XetOp *xet_test_make_void_op(void);

XetOp *xet_test_make_error_op(void);

/**
 * Install xet's tracing subscriber. `version` may be NULL.
 *
 * # Safety
 * `version` must be null or a valid NUL-terminated C string.
 */
void xet_init_logging(const char *version);

/**
 * Create a new session. Writes the handle to `*out`.
 *
 * # Safety
 * `out` must be a valid pointer to write the handle to; `err` may be null.
 */
XetStatus xet_session_new(XetSession **out, XetError **err);

void xet_session_free(XetSession *session);

/**
 * # Safety
 * `commit` must be a valid handle; `path` a valid C string; `provided_sha256`
 * null or valid; `out`/`err` valid pointers.
 */
XetStatus xet_upload_commit_upload_from_path(const XetUploadCommit *commit,
                                             const char *path,
                                             XetSha256Policy policy,
                                             const char *provided_sha256,
                                             XetFileUpload **out,
                                             XetError **err);

/**
 * # Safety
 * `commit` valid; `data`/`len` a valid buffer (data may be null iff len==0);
 * `name`/`provided_sha256` null or valid; `out`/`err` valid.
 */
XetStatus xet_upload_commit_upload_bytes(const XetUploadCommit *commit,
                                         const uint8_t *data,
                                         uintptr_t len,
                                         const char *name,
                                         XetSha256Policy policy,
                                         const char *provided_sha256,
                                         XetFileUpload **out,
                                         XetError **err);

/**
 * Begin a streaming upload. `name` (nullable) is a tracking name.
 *
 * # Safety
 * `commit` valid; `name`/`provided_sha256` null or valid; `out`/`err` valid.
 */
XetStatus xet_upload_commit_upload_stream(const XetUploadCommit *commit,
                                          const char *name,
                                          XetSha256Policy policy,
                                          const char *provided_sha256,
                                          XetStreamUpload **out,
                                          XetError **err);

/**
 * # Safety
 * `upload` valid; `out`/`err` valid pointers.
 */
XetStatus xet_file_upload_finalize_start(const XetFileUpload *upload, XetOp **out, XetError **err);

/**
 * # Safety
 * `commit` valid; `out`/`err` valid pointers.
 */
XetStatus xet_upload_commit_commit_start(const XetUploadCommit *commit,
                                         XetOp **out,
                                         XetError **err);

/**
 * # Safety
 * `commit` valid; `out` a valid pointer to a `XetProgress`.
 */
XetStatus xet_upload_commit_progress(const XetUploadCommit *commit, XetProgress *out);

/**
 * # Safety
 * `commit` valid; `err` valid.
 */
XetStatus xet_upload_commit_abort(const XetUploadCommit *commit, XetError **err);

/**
 * # Safety
 * `m` must be null or a valid metadata handle.
 */
const char *xet_file_metadata_hash(const XetFileMetadataHandle *m);

/**
 * # Safety
 * `m` must be null or a valid metadata handle.
 */
uint64_t xet_file_metadata_file_size(const XetFileMetadataHandle *m);

/**
 * Returns NULL if no sha256 is present.
 *
 * # Safety
 * `m` must be null or a valid metadata handle.
 */
const char *xet_file_metadata_sha256(const XetFileMetadataHandle *m);

/**
 * Returns NULL if no tracking name is present.
 *
 * # Safety
 * `m` must be null or a valid metadata handle.
 */
const char *xet_file_metadata_tracking_name(const XetFileMetadataHandle *m);

/**
 * Free an OWNED metadata handle (from `xet_op_take_file_metadata`). Do NOT call
 * on a borrowed handle returned by a report accessor.
 */
void xet_file_metadata_free(XetFileMetadataHandle *m);

void xet_upload_commit_free(XetUploadCommit *commit);

void xet_file_upload_free(XetFileUpload *upload);

/**
 * Start an async write of `len` bytes from `data`. Poll the returned op; it
 * yields void on success.
 *
 * # Safety
 * `su` valid; `data`/`len` a valid buffer (data may be null iff len==0);
 * `out`/`err` valid pointers.
 */
XetStatus xet_stream_upload_write_start(const XetStreamUpload *su,
                                        const uint8_t *data,
                                        uintptr_t len,
                                        XetOp **out,
                                        XetError **err);

/**
 * Start finalizing the stream. Poll the returned op; it yields file metadata.
 *
 * # Safety
 * `su` valid; `out`/`err` valid pointers.
 */
XetStatus xet_stream_upload_finish_start(const XetStreamUpload *su, XetOp **out, XetError **err);

void xet_stream_upload_free(XetStreamUpload *su);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HF_XET_H */
