/* Generated by cbindgen from xet_capi. DO NOT EDIT BY HAND. */

#ifndef HF_XET_H
#define HF_XET_H

/* Regenerate with `cargo build -p xet_capi`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status returned by every fallible `xet_*` function.
 */
typedef enum {
    XetStatus_XetOk = 0,
    XetStatus_XetErr = 1,
    XetStatus_XetErrInvalidArg = 2,
    XetStatus_XetErrAuth = 3,
    XetStatus_XetErrNotFound = 4,
    XetStatus_XetErrCancelled = 5,
    XetStatus_XetErrPanic = 6,
} XetStatus;

typedef enum {
    XetPollState_XetPollPending = 0,
    XetPollState_XetPollReady = 1,
    XetPollState_XetPollError = 2,
} XetPollState;

/**
 * An owned byte buffer produced by streaming downloads. Read via
 * [`xet_bytes_data`] / [`xet_bytes_len`]; free with [`xet_bytes_free`].
 */
typedef struct XetBytes XetBytes;

/**
 * Opaque error object. Read via [`xet_error_message`] / [`xet_error_code`];
 * free with [`xet_error_free`].
 */
typedef struct XetError XetError;

/**
 * A spawned, poll-able operation. Poll with [`xet_op_poll`], then consume with
 * the matching `xet_op_take_*`. Free an un-taken op with [`xet_op_free`].
 */
typedef struct XetOp XetOp;

/**
 * A Xet session. Owns no auth; produces per-commit / per-group auth via the
 * `xet_session_new_*` builders (added in a later task). Free with
 * [`xet_session_free`].
 */
typedef struct XetSession XetSession;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the xet_capi version as a static NUL-terminated C string.
 */
const char *xet_version(void);

/**
 * # Safety
 * `b` must be null or a valid pointer to a live `XetBytes` produced by this crate.
 */
const unsigned char *xet_bytes_data(const XetBytes *b);

/**
 * # Safety
 * `b` must be null or a valid pointer to a live `XetBytes` produced by this crate.
 */
uintptr_t xet_bytes_len(const XetBytes *b);

void xet_bytes_free(XetBytes *b);

/**
 * Test-only constructor used by ffi_tests.
 */
XetBytes *xet_test_make_bytes(void);

/**
 * # Safety
 * `err` must be null or a valid pointer to a live `XetError` produced by this crate.
 */
XetStatus xet_error_code(const XetError *err);

/**
 * # Safety
 * `err` must be null or a valid pointer to a live `XetError` produced by this crate.
 */
const char *xet_error_message(const XetError *err);

/**
 * # Safety
 * `err` must be null or a pointer previously returned by this crate that has not
 * already been freed.
 */
void xet_error_free(XetError *err);

/**
 * Test-only constructor used by ffi_tests.
 *
 * # Safety
 * `out` must be a valid, non-null pointer to a writable `*mut XetError`.
 */
int xet_test_make_auth_error(XetError **out);

/**
 * # Safety
 * `op` must be null or a valid pointer to a live `XetOp` produced by this crate.
 */
XetPollState xet_op_poll(const XetOp *op);

/**
 * # Safety
 * `op` must be null or a pointer previously returned by this crate that has not
 * already been freed or consumed by a `xet_op_take_*` call.
 */
void xet_op_free(XetOp *op);

/**
 * Extract a `XetError` from a failed op. Returns `XET_OK` and fills `*err`;
 * returns `XET_ERR_INVALID_ARG` if the op did not fail.
 *
 * # Safety
 * `op` must be a valid pointer to a live `XetOp`; `err` must be null or a valid
 * writable `*mut XetError`.
 */
XetStatus xet_op_take_error(XetOp *op, XetError **err);

/**
 * Void ops (e.g. stream write) — no payload.
 *
 * # Safety
 * `op` must be a valid pointer to a live `XetOp`; `err` must be null or a valid
 * writable `*mut XetError`.
 */
XetStatus xet_op_take_void(XetOp *op, XetError **err);

/**
 * Ordered stream chunk. On success `*out` is a `XetBytes*`, or NULL at EOF.
 *
 * # Safety
 * `op` must be a valid pointer to a live `XetOp`; `out` and `err` must be null
 * or valid writable out-pointers.
 */
XetStatus xet_op_take_bytes(XetOp *op, XetBytes **out, XetError **err);

/**
 * Unordered stream chunk. On success fills `*offset` and `*out` (NULL at EOF).
 *
 * # Safety
 * `op` must be a valid pointer to a live `XetOp`; `offset`, `out`, and `err`
 * must be null or valid writable out-pointers.
 */
XetStatus xet_op_take_chunk(XetOp *op, uint64_t *offset, XetBytes **out, XetError **err);

XetOp *xet_test_make_void_op(void);

XetOp *xet_test_make_error_op(void);

/**
 * Install xet's tracing subscriber. `version` may be NULL.
 *
 * # Safety
 * `version` must be null or a valid NUL-terminated C string.
 */
void xet_init_logging(const char *version);

/**
 * Create a new session. Writes the handle to `*out`.
 *
 * # Safety
 * `out` must be a valid pointer to write the handle to; `err` may be null.
 */
XetStatus xet_session_new(XetSession **out, XetError **err);

void xet_session_free(XetSession *session);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HF_XET_H */
