/* Generated by cbindgen from xet_capi. DO NOT EDIT BY HAND. */

#ifndef HF_XET_H
#define HF_XET_H

/* Regenerate with `cargo build -p xet_capi`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status returned by every fallible `xet_*` function.
 */
typedef enum {
    /**
     * The call succeeded; any `out` pointers were filled in.
     */
    XetStatus_XetOk = 0,
    /**
     * The call failed for a reason not covered by a more specific variant.
     * Check the accompanying `XetError` (if any) for details.
     */
    XetStatus_XetErr = 1,
    /**
     * A required argument was null, malformed, or otherwise invalid (e.g. a
     * bad hash string, a handle that failed a null check).
     */
    XetStatus_XetErrInvalidArg = 2,
    /**
     * The call failed due to missing, expired, or rejected credentials.
     */
    XetStatus_XetErrAuth = 3,
    /**
     * The requested resource (file, hash, etc.) does not exist.
     */
    XetStatus_XetErrNotFound = 4,
    /**
     * The operation was cancelled before completing.
     */
    XetStatus_XetErrCancelled = 5,
    /**
     * A Rust panic was caught at the FFI boundary and converted into this
     * status; no partial state should be assumed to be valid.
     */
    XetStatus_XetErrPanic = 6,
} XetStatus;

/**
 * SHA-256 handling for uploads.
 */
typedef enum {
    /**
     * Compute the SHA-256 from the upload data as it is read.
     */
    XetSha256Policy_XetSha256Compute = 0,
    /**
     * Skip SHA-256 entirely; the resulting metadata will have no SHA-256.
     */
    XetSha256Policy_XetSha256Skip = 1,
    /**
     * Use a caller-supplied SHA-256 (hex) instead of computing one. The hex
     * string is passed via the `provided_sha256` parameter of the calling
     * function and is not validated against the actual upload contents.
     */
    XetSha256Policy_XetSha256Provided = 2,
} XetSha256Policy;

/**
 * An owned byte buffer produced by streaming downloads. Read via
 * [`xet_bytes_data`] / [`xet_bytes_len`]; free with [`xet_bytes_free`].
 */
typedef struct XetBytes XetBytes;

/**
 * Owned commit report. Free with [`xet_commit_report_free`].
 */
typedef struct XetCommitReportHandle XetCommitReportHandle;

/**
 * Owned download-group report. Free with [`xet_download_group_report_free`].
 */
typedef struct XetDownloadGroupReportHandle XetDownloadGroupReportHandle;

/**
 * An active download stream (ordered or unordered). `next` requires `&mut`,
 * so the inner stream is guarded by a mutex; calls on the handle from other
 * threads (progress/cancel) wait for the in-flight `next` to return. Free
 * with [`xet_download_stream_free`].
 */
typedef struct XetDownloadStream XetDownloadStream;

/**
 * A stream-download group. Free with [`xet_download_stream_group_free`].
 */
typedef struct XetDownloadStreamGroup XetDownloadStreamGroup;

/**
 * Opaque error object. Read via [`xet_error_message`] / [`xet_error_code`];
 * free with [`xet_error_free`].
 */
typedef struct XetError XetError;

/**
 * A queued file download. Free with [`xet_file_download_free`].
 */
typedef struct XetFileDownload XetFileDownload;

/**
 * A file-download group (Arc-backed; cheap to clone). Free with
 * [`xet_file_download_group_free`].
 */
typedef struct XetFileDownloadGroup XetFileDownloadGroup;

/**
 * File descriptor for downloads. Free with [`xet_file_info_free`].
 */
typedef struct XetFileInfo XetFileInfo;

/**
 * Per-file metadata result. C strings are prebuilt at construction so accessor
 * pointers stay valid until the handle is freed. Free OWNED handles (e.g. from
 * `xet_file_upload_finalize`) with [`xet_file_metadata_free`]; borrowed views
 * returned by report accessors must NOT be freed.
 */
typedef struct XetFileMetadataHandle XetFileMetadataHandle;

/**
 * A queued file upload. Free with [`xet_file_upload_free`].
 */
typedef struct XetFileUpload XetFileUpload;

/**
 * A Xet session. Owns no auth; produces per-commit / per-group auth via the
 * `xet_session_new_*` builders (added in a later task). Free with
 * [`xet_session_free`].
 */
typedef struct XetSession XetSession;

/**
 * A streaming upload handle. Feed data with [`xet_stream_upload_write`], then
 * [`xet_stream_upload_finish`]. Free with [`xet_stream_upload_free`].
 */
typedef struct XetStreamUpload XetStreamUpload;

/**
 * An upload commit (Arc-backed; cheap to clone). Free with [`xet_upload_commit_free`].
 */
typedef struct XetUploadCommit XetUploadCommit;

/**
 * Flat progress snapshot (all scalar; stable layout).
 */
typedef struct {
    uint64_t total_bytes;
    uint64_t total_bytes_completed;
    uint64_t total_transfer_bytes;
    uint64_t total_transfer_bytes_completed;
} XetProgress;

/**
 * Flat dedup metrics snapshot.
 */
typedef struct {
    uint64_t total_bytes;
    uint64_t deduped_bytes;
    uint64_t new_bytes;
    uint64_t deduped_bytes_by_global_dedup;
    uint64_t total_chunks;
    uint64_t deduped_chunks;
    uint64_t new_chunks;
    uint64_t xorb_bytes_uploaded;
    uint64_t shard_bytes_uploaded;
    uint64_t total_bytes_uploaded;
} XetDedupMetrics;

/**
 * One HTTP header for token-refresh requests. Both pointers are borrowed
 * NUL-terminated C strings, valid only for the duration of the call that
 * takes an array of `XetHeader`s (e.g. via `XetAuthConfig::refresh_headers`).
 */
typedef struct {
    /**
     * Header name, e.g. `"Authorization"`.
     */
    const char *key;
    /**
     * Header value.
     */
    const char *value;
} XetHeader;

/**
 * Per-commit / per-group auth configuration. All pointers are borrowed for
 * the duration of the call. Any nullable field may be NULL.
 */
typedef struct {
    /**
     * Hub endpoint URL, e.g. `"https://huggingface.co"`. Must not be NULL.
     */
    const char *endpoint;
    /**
     * Bearer token used for CAS/Hub requests. Must not be NULL.
     */
    const char *token;
    /**
     * Unix timestamp (seconds) at which `token` expires, or `0`/negative if
     * it never needs refreshing.
     */
    int64_t token_expiry;
    /**
     * URL to POST to for a token refresh. NULL disables refreshing.
     */
    const char *token_refresh_url;
    /**
     * Borrowed array of `refresh_header_count` headers sent with each
     * refresh request. May be NULL iff `refresh_header_count == 0`.
     */
    const XetHeader *refresh_headers;
    /**
     * Number of entries in `refresh_headers`.
     */
    uintptr_t refresh_header_count;
} XetAuthConfig;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the xet_capi version as a static NUL-terminated C string.
 */
const char *xet_version(void);

/**
 * # Safety
 * `b` must be null or a valid pointer to a live `XetBytes` produced by this crate.
 */
const unsigned char *xet_bytes_data(const XetBytes *b);

/**
 * # Safety
 * `b` must be null or a valid pointer to a live `XetBytes` produced by this crate.
 */
uintptr_t xet_bytes_len(const XetBytes *b);

/**
 * Free a `XetBytes` buffer. Safe to call with null.
 */
void xet_bytes_free(XetBytes *b);

/**
 * Test-only constructor used by ffi_tests.
 */
XetBytes *xet_test_make_bytes(void);

/**
 * Queue a file for download to `dest_path`. Returns a handle immediately;
 * call `xet_file_download_group_finish` to await all downloads.
 *
 * # Safety
 * `group`/`file_info` valid handles; `dest_path` a valid C string; `out`/`err` valid.
 */
XetStatus xet_file_download_group_download_to_path(const XetFileDownloadGroup *group,
                                                   const XetFileInfo *file_info,
                                                   const char *dest_path,
                                                   XetFileDownload **out,
                                                   XetError **err);

/**
 * Await all queued downloads, blocking until complete. On success fills
 * `*out` with an owned `XetDownloadGroupReportHandle` (free with
 * `xet_download_group_report_free`).
 *
 * Blocks the calling thread for the full duration. Progress can be observed
 * concurrently from another thread via [`xet_file_download_group_progress`];
 * [`xet_file_download_group_abort`] may be called from another thread to
 * cancel.
 *
 * # Safety
 * `group`/`out`/`err` valid pointers.
 */
XetStatus xet_file_download_group_finish(const XetFileDownloadGroup *group,
                                         XetDownloadGroupReportHandle **out,
                                         XetError **err);

/**
 * # Safety
 * `group` valid; `out` a valid pointer to a `XetProgress`.
 */
XetStatus xet_file_download_group_progress(const XetFileDownloadGroup *group, XetProgress *out);

/**
 * # Safety
 * `group` valid; `err` valid.
 */
XetStatus xet_file_download_group_abort(const XetFileDownloadGroup *group, XetError **err);

/**
 * Returns the download's task id, or 0 if `download` is null.
 *
 * # Safety
 * `download` must be null or a valid handle.
 */
uint64_t xet_file_download_task_id(const XetFileDownload *download);

/**
 * Free a `XetFileDownloadGroup`. Safe to call with null.
 */
void xet_file_download_group_free(XetFileDownloadGroup *group);

/**
 * Free a `XetFileDownload`. Safe to call with null.
 */
void xet_file_download_free(XetFileDownload *download);

/**
 * # Safety
 * `group`/`file_info` valid; `out`/`err` valid pointers.
 */
XetStatus xet_download_stream_group_download_stream(const XetDownloadStreamGroup *group,
                                                    const XetFileInfo *file_info,
                                                    bool has_range,
                                                    uint64_t range_start,
                                                    uint64_t range_end,
                                                    XetDownloadStream **out,
                                                    XetError **err);

/**
 * # Safety
 * `group`/`file_info` valid; `out`/`err` valid pointers.
 */
XetStatus xet_download_stream_group_download_unordered_stream(const XetDownloadStreamGroup *group,
                                                              const XetFileInfo *file_info,
                                                              bool has_range,
                                                              uint64_t range_start,
                                                              uint64_t range_end,
                                                              XetDownloadStream **out,
                                                              XetError **err);

/**
 * Fetch the next chunk, blocking until it is available. On success `*out` is
 * a `XetBytes*` (free with `xet_bytes_free`), or NULL at end of stream.
 *
 * - Ordered streams: chunks arrive in file order; `*offset` is not written (`offset` may be NULL).
 * - Unordered streams: `*offset` receives the chunk's byte offset in the file.
 *
 * Blocks the calling thread until the chunk arrives. The stream handle is
 * internally serialized: [`xet_download_stream_progress`] and
 * [`xet_download_stream_cancel`] called from other threads will wait until
 * the in-flight `xet_download_stream_next` returns.
 *
 * # Safety
 * `stream` valid; `offset` null or a valid writable pointer; `out`/`err`
 * valid pointers.
 */
XetStatus xet_download_stream_next(const XetDownloadStream *stream,
                                   uint64_t *offset,
                                   XetBytes **out,
                                   XetError **err);

/**
 * # Safety
 * `stream` valid; `out` a valid pointer to a `XetProgress`.
 */
XetStatus xet_download_stream_progress(const XetDownloadStream *stream, XetProgress *out);

/**
 * # Safety
 * `stream` must be null or a valid handle.
 */
void xet_download_stream_cancel(const XetDownloadStream *stream);

/**
 * Returns the stream's task id, or 0 if `stream` is null.
 *
 * # Safety
 * `stream` must be null or a valid handle.
 */
uint64_t xet_download_stream_task_id(const XetDownloadStream *stream);

/**
 * Free a `XetDownloadStreamGroup`. Safe to call with null.
 */
void xet_download_stream_group_free(XetDownloadStreamGroup *group);

/**
 * Free a `XetDownloadStream`. Safe to call with null.
 */
void xet_download_stream_free(XetDownloadStream *stream);

/**
 * # Safety
 * `err` must be null or a valid pointer to a live `XetError` produced by this crate.
 */
XetStatus xet_error_code(const XetError *err);

/**
 * # Safety
 * `err` must be null or a valid pointer to a live `XetError` produced by this crate.
 */
const char *xet_error_message(const XetError *err);

/**
 * # Safety
 * `err` must be null or a pointer previously returned by this crate that has not
 * already been freed.
 */
void xet_error_free(XetError *err);

/**
 * Test-only constructor used by ffi_tests.
 *
 * # Safety
 * `out` must be a valid, non-null pointer to a writable `*mut XetError`.
 */
int xet_test_make_auth_error(XetError **out);

/**
 * Create a file descriptor from a xet content hash (hex) and size.
 *
 * # Safety
 * `hash` must be a valid NUL-terminated C string; `out` a valid pointer.
 */
XetStatus xet_file_info_new(const char *hash,
                            uint64_t file_size,
                            XetFileInfo **out,
                            XetError **err);

/**
 * Like [`xet_file_info_new`] but with a known SHA-256 (hex).
 *
 * # Safety
 * `hash` and `sha256` must be valid NUL-terminated C strings; `out` valid.
 */
XetStatus xet_file_info_new_with_sha256(const char *hash,
                                        uint64_t file_size,
                                        const char *sha256,
                                        XetFileInfo **out,
                                        XetError **err);

/**
 * Free a `XetFileInfo`. Safe to call with null.
 */
void xet_file_info_free(XetFileInfo *fi);

/**
 * # Safety
 * `r` must be null or a valid commit-report handle.
 */
uintptr_t xet_commit_report_file_count(const XetCommitReportHandle *r);

/**
 * Borrow the i-th file metadata. The returned pointer is valid until the
 * report is freed; do NOT pass it to `xet_file_metadata_free`.
 *
 * # Safety
 * `r` valid; `out` a valid pointer.
 */
XetStatus xet_commit_report_file_at(const XetCommitReportHandle *r,
                                    uintptr_t index,
                                    const XetFileMetadataHandle **out);

/**
 * # Safety
 * `r` valid; `out` a valid pointer to a `XetDedupMetrics`.
 */
XetStatus xet_commit_report_dedup(const XetCommitReportHandle *r, XetDedupMetrics *out);

/**
 * # Safety
 * `r` valid; `out` a valid pointer to a `XetProgress`.
 */
XetStatus xet_commit_report_progress(const XetCommitReportHandle *r, XetProgress *out);

/**
 * Free a `XetCommitReportHandle`. Safe to call with null.
 */
void xet_commit_report_free(XetCommitReportHandle *r);

/**
 * # Safety
 * `r` must be null or a valid download-group-report handle.
 */
uintptr_t xet_download_group_report_count(const XetDownloadGroupReportHandle *r);

/**
 * Fill `*task_id` and `*bytes_completed` for the i-th download.
 *
 * # Safety
 * `r` valid; `task_id`/`bytes_completed` may be null (skipped) or valid.
 */
XetStatus xet_download_group_report_at(const XetDownloadGroupReportHandle *r,
                                       uintptr_t index,
                                       uint64_t *task_id,
                                       uint64_t *bytes_completed);

/**
 * Free a `XetDownloadGroupReportHandle`. Safe to call with null.
 */
void xet_download_group_report_free(XetDownloadGroupReportHandle *r);

/**
 * Create a new session. Writes the handle to `*out`.
 *
 * # Safety
 * `out` must be a valid pointer to write the handle to; `err` may be null.
 */
XetStatus xet_session_new(XetSession **out, XetError **err);

/**
 * Free a `XetSession`. Safe to call with null.
 */
void xet_session_free(XetSession *session);

/**
 * Build an upload commit with per-commit auth from `cfg`.
 *
 * # Safety
 * `session`/`cfg` valid handles/pointers; `out`/`err` valid pointers.
 */
XetStatus xet_session_new_upload_commit(const XetSession *session,
                                        const XetAuthConfig *cfg,
                                        XetUploadCommit **out,
                                        XetError **err);

/**
 * Build a file-download group with per-group auth from `cfg`.
 *
 * # Safety
 * `session`/`cfg` valid; `out`/`err` valid pointers.
 */
XetStatus xet_session_new_file_download_group(const XetSession *session,
                                              const XetAuthConfig *cfg,
                                              XetFileDownloadGroup **out,
                                              XetError **err);

/**
 * Build a download-stream group with per-group auth from `cfg`.
 *
 * # Safety
 * `session`/`cfg` valid; `out`/`err` valid pointers.
 */
XetStatus xet_session_new_download_stream_group(const XetSession *session,
                                                const XetAuthConfig *cfg,
                                                XetDownloadStreamGroup **out,
                                                XetError **err);

/**
 * # Safety
 * `commit` must be a valid handle; `path` a valid C string; `provided_sha256`
 * null or valid; `out`/`err` valid pointers.
 */
XetStatus xet_upload_commit_upload_from_path(const XetUploadCommit *commit,
                                             const char *path,
                                             XetSha256Policy policy,
                                             const char *provided_sha256,
                                             XetFileUpload **out,
                                             XetError **err);

/**
 * # Safety
 * `commit` valid; `data`/`len` a valid buffer (data may be null iff len==0);
 * `name`/`provided_sha256` null or valid; `out`/`err` valid.
 */
XetStatus xet_upload_commit_upload_bytes(const XetUploadCommit *commit,
                                         const uint8_t *data,
                                         uintptr_t len,
                                         const char *name,
                                         XetSha256Policy policy,
                                         const char *provided_sha256,
                                         XetFileUpload **out,
                                         XetError **err);

/**
 * Begin a streaming upload. `name` (nullable) is a tracking name.
 *
 * # Safety
 * `commit` valid; `name`/`provided_sha256` null or valid; `out`/`err` valid.
 */
XetStatus xet_upload_commit_upload_stream(const XetUploadCommit *commit,
                                          const char *name,
                                          XetSha256Policy policy,
                                          const char *provided_sha256,
                                          XetStreamUpload **out,
                                          XetError **err);

/**
 * Finalize this file's ingestion, blocking until complete. On success fills
 * `*out` with an owned `XetFileMetadataHandle` (free with
 * [`xet_file_metadata_free`]).
 *
 * Blocks the calling thread for the full duration. Progress can be observed
 * concurrently from another thread via [`xet_upload_commit_progress`].
 *
 * # Safety
 * `upload` valid; `out`/`err` valid pointers.
 */
XetStatus xet_file_upload_finalize(const XetFileUpload *upload,
                                   XetFileMetadataHandle **out,
                                   XetError **err);

/**
 * Commit all finalized uploads, blocking until complete. On success fills
 * `*out` with an owned `XetCommitReportHandle` (free with
 * [`xet_commit_report_free`]).
 *
 * Blocks the calling thread for the full duration. Progress can be observed
 * concurrently from another thread via [`xet_upload_commit_progress`];
 * [`xet_upload_commit_abort`] may be called from another thread to cancel.
 *
 * # Safety
 * `commit` valid; `out`/`err` valid pointers.
 */
XetStatus xet_upload_commit_commit(const XetUploadCommit *commit,
                                   XetCommitReportHandle **out,
                                   XetError **err);

/**
 * # Safety
 * `commit` valid; `out` a valid pointer to a `XetProgress`.
 */
XetStatus xet_upload_commit_progress(const XetUploadCommit *commit, XetProgress *out);

/**
 * # Safety
 * `commit` valid; `err` valid.
 */
XetStatus xet_upload_commit_abort(const XetUploadCommit *commit, XetError **err);

/**
 * # Safety
 * `m` must be null or a valid metadata handle.
 */
const char *xet_file_metadata_hash(const XetFileMetadataHandle *m);

/**
 * # Safety
 * `m` must be null or a valid metadata handle.
 */
uint64_t xet_file_metadata_file_size(const XetFileMetadataHandle *m);

/**
 * Returns NULL if no sha256 is present.
 *
 * # Safety
 * `m` must be null or a valid metadata handle.
 */
const char *xet_file_metadata_sha256(const XetFileMetadataHandle *m);

/**
 * Returns NULL if no tracking name is present.
 *
 * # Safety
 * `m` must be null or a valid metadata handle.
 */
const char *xet_file_metadata_tracking_name(const XetFileMetadataHandle *m);

/**
 * Free an OWNED metadata handle (e.g. from `xet_file_upload_finalize`). Do NOT
 * call on a borrowed handle returned by a report accessor.
 */
void xet_file_metadata_free(XetFileMetadataHandle *m);

/**
 * Free a `XetUploadCommit`. Safe to call with null.
 */
void xet_upload_commit_free(XetUploadCommit *commit);

/**
 * Free a `XetFileUpload`. Safe to call with null.
 */
void xet_file_upload_free(XetFileUpload *upload);

/**
 * Write `len` bytes from `data` into the stream, blocking until the write is
 * ingested.
 *
 * # Safety
 * `su` valid; `data`/`len` a valid buffer (data may be null iff len==0);
 * `err` a valid pointer.
 */
XetStatus xet_stream_upload_write(const XetStreamUpload *su,
                                  const uint8_t *data,
                                  uintptr_t len,
                                  XetError **err);

/**
 * Finalize the stream, blocking until complete. On success fills `*out` with
 * an owned `XetFileMetadataHandle` (free with `xet_file_metadata_free`).
 *
 * # Safety
 * `su` valid; `out`/`err` valid pointers.
 */
XetStatus xet_stream_upload_finish(const XetStreamUpload *su,
                                   XetFileMetadataHandle **out,
                                   XetError **err);

/**
 * Free a `XetStreamUpload`. Safe to call with null.
 */
void xet_stream_upload_free(XetStreamUpload *su);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HF_XET_H */
