[package]
name = "cas_types"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.208", features = ["derive"] }
merklehash = { path = "../merklehash" }
serde_repr = "0.1.19"
