[package]
name = "cas_types"
version = "0.1.0"
edition = "2021"

[dependencies]
merklehash = { path = "../merklehash" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
derivative = { workspace = true }
