name: hf-xet prerelease testing
# This workflow is triggered when a new pre-release build is triggered by the release workflow. 

on:
  push:
    tags:
      - v*rc*
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to test (e.g., v1.0.3-rc2)"
        required: true
jobs:
  trigger_rc_testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target-repo: ["huggingface_hub"]

    steps:
      - name: Determine PyPi version from tag
        id: get-version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TAG=${{ inputs.tag }}
          else
            TAG=${GITHUB_REF#refs/tags/}
          fi
          SEM_VERSION=${TAG#v}
          TRIMMED_VERSION=${SEM_VERSION//-}
          echo "VERSION=${TRIMMED_VERSION}" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=ci_test_hf_xet_${TRIMMED_VERSION}_release" >> $GITHUB_OUTPUT

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: huggingface/${{ matrix.target-repo }}
          path: ${{ matrix.target-repo }}
          token: ${{ secrets.TOKEN_HUGGINGFACE_HUB_AUTO_BY_XET }}

      - name: Configure Git
        run: |
          cd ${{ matrix.target-repo }}
          git config user.name "Hugging Face Bot (Xet RC Testing)"
          git config user.email "bot+xet@huggingface.co"

      - name: Wait for prerelease to be out on PyPI
        run: |
          VERSION=${{ steps.get-version.outputs.VERSION }}
          echo "Waiting for hf_xet==${VERSION} to be available on PyPI"
          while ! pip install hf_xet==${VERSION}; do
            echo "hf_xet==${VERSION} not available yet, retrying in 15s"
            sleep 15
          done

      - name: Create test branch and update dependencies
        id: create-pr
        run: |
          cd ${{ matrix.target-repo }}
          VERSION=${{ steps.get-version.outputs.VERSION }}
          BRANCH_NAME=${{ steps.get-version.outputs.BRANCH_NAME }}

          # Create and checkout new branch
          git checkout -b $BRANCH_NAME

          # Update hf_xet dependency to use the fixed rc version
          sed -i -E "s/hf(_|-)xet(>|<|=)=(([0-9]+\.[0-9]+\.[0-9]+)|([0-9]+\.[0-9]+\.[0-9]+,<[0-9]+\.[0-9]+\.[0-9]+))/hf_xet==${VERSION}/g" setup.py
          git add setup.py

          # Any line with `uv pip install --prerelease=allow` in the `.github/` folder must be updated with `--prerelease=allow` flag
          find .github/workflows/ -type f -exec sed -i 's/uv pip install /uv pip install --prerelease=allow /g' {} +
          git add .github/workflows/

          # Commit and push changes
          git --no-pager diff --staged
          git commit -m "Test hfh ${VERSION}"
          git push --set-upstream origin $BRANCH_NAME

      - name: Print URLs for manual check
        run: |
          VERSION=${{ steps.get-version.outputs.VERSION }}
          BRANCH_NAME=${{ steps.get-version.outputs.BRANCH_NAME }}
          echo "https://github.com/huggingface/${{ matrix.target-repo }}/actions"
          echo "https://github.com/huggingface/${{matrix.target-repo}}/tree/refs/heads/${BRANCH_NAME}"
          echo "https://github.com/huggingface/huggingface_hub/${{ matrix.target-repo }}/compare/main...${BRANCH_NAME}"
